#!/bin/bash

# Navega al directorio donde se encuentra tu proyecto de Node.js
cd ~
cd Ubicuos/recogedorUsuarios

# Ejecuta el comando npm run start en segundo plano
npm run start:dev_linux &

# Espera unos segundos para asegurarse de que el servidor Node.js esté funcionando
sleep 7

# Realiza la solicitud GET con curl al servidor local
curl -v http://localhost:5000/users


